### ISSUE TITLE
Crash !?

### ISSUE THREAD

**Issue by ShadyGaDa** [Magisk-Modules-Repo/iYTBP-Vanced-black-Magisk-Repo#3]
YouTube has stopped

Here is logcat

<<< log_count = 44 >>>
[10-27 12:46:21.521 818:818 I/PackageManager]
/system/app/YouTube changed; collecting certs

[10-27 12:47:01.345 818:858 I/ActivityManager]
Start proc 2489:com.google.android.youtube/u0a183 for broadcast com.google.android.youtube/com.google.android.libraries.youtube.mdx.background.MdxBackgroundScanBootReceiver

[10-27 12:47:01.360 274:397 I/Magisk]
proc_monitor: com.google.android.youtube

[10-27 12:47:01.520 2489:2489 W/System]
ClassLoader referenced unknown path: /system/app/YouTube/Youtube.apk

[10-27 12:47:01.546 2489:2489 W/asset]
Asset path /system/app/YouTube/Youtube.apk is neither a directory nor file (type=1).

[10-27 12:47:01.546 2489:2489 E/ResourcesManager]
failed to add asset path /system/app/YouTube/Youtube.apk

[10-27 12:47:01.547 2489:2489 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: com.google.android.youtube, PID: 2489
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference
	at android.app.ActivityThread.updateLocaleListFromAppContext(ActivityThread.java:5414)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5640)
	at android.app.ActivityThread.-wrap1(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

[10-27 12:47:01.663 818:907 I/ActivityManager]
Showing crash dialog for package com.google.android.youtube u0

[10-27 12:47:07.079 818:858 I/ActivityManager]
Killing 2489:com.google.android.youtube/u0a183 (adj 0): crash

[10-27 12:47:07.104 818:906 I/ActivityManager]
Start proc 2528:com.google.android.youtube/u0a183 for broadcast com.google.android.youtube/com.google.android.libraries.youtube.mdx.notification.LocalNotificationsBroadcastReceiver

[10-27 12:47:07.118 274:397 I/Magisk]
proc_monitor: com.google.android.youtube

[10-27 12:47:07.211 2528:2528 W/System]
ClassLoader referenced unknown path: /system/app/YouTube/Youtube.apk

[10-27 12:47:07.218 2528:2528 W/asset]
Asset path /system/app/YouTube/Youtube.apk is neither a directory nor file (type=1).

[10-27 12:47:07.218 2528:2528 E/ResourcesManager]
failed to add asset path /system/app/YouTube/Youtube.apk

[10-27 12:47:07.220 2528:2528 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: com.google.android.youtube, PID: 2528
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference
	at android.app.ActivityThread.updateLocaleListFromAppContext(ActivityThread.java:5414)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5640)
	at android.app.ActivityThread.-wrap1(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

[10-27 12:47:07.226 818:858 W/ActivityManager]
Process com.google.android.youtube has crashed too many times: killing!

[10-27 12:47:07.227 818:858 I/ActivityManager]
Killing 2528:com.google.android.youtube/u0a183 (adj 0): crash

[10-27 12:47:20.872 1960:2021 D/InstalledAppProviderSer]
insertAppIntoDb com.google.android.youtube

[10-27 12:47:27.656 3709:3709 I/dex2oat]
/system/bin/dex2oat --input-vdex-fd=-1 --output-vdex-fd=9 --compiler-filter=verify --classpath-dir=/system/app/YouTube --class-loader-context=PCL[]

[10-27 13:02:32.165 2090:2090 D/Launchy]
intent:Intent { act=android.intent.action.PACKAGE_CHANGED dat=package:com.google.android.youtube flg=0x45000010 (has extras) }, data: package:com.google.android.youtube

[10-27 13:02:32.177 2090:2090 D/Launchy]
packageIntent Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.google.android.youtube cmp=com.google.android.youtube/.app.honeycomb.Shell$HomeActivity }

[10-27 13:02:32.177 2090:2090 I/InstallCatch]
The installed package is: com.google.android.youtube

[10-27 13:02:32.183 1495:1495 D/ImsResolver]
maybeAddedImsService, packageName: com.google.android.youtube

[10-27 13:02:37.570 1495:1495 D/ImsResolver]
maybeAddedImsService, packageName: com.google.android.youtube

[10-27 13:02:37.571 2090:2090 D/Launchy]
intent:Intent { act=android.intent.action.PACKAGE_CHANGED dat=package:com.google.android.youtube flg=0x45000010 (has extras) }, data: package:com.google.android.youtube

[10-27 13:02:37.578 2090:2090 D/Launchy]
packageIntent Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.google.android.youtube cmp=com.google.android.youtube/.app.honeycomb.Shell$HomeActivity }

[10-27 13:02:37.578 2090:2090 I/InstallCatch]
The installed package is: com.google.android.youtube

[10-27 13:02:46.112 2090:2090 D/Launchy]
intent:Intent { act=android.intent.action.PACKAGE_CHANGED dat=package:com.google.android.youtube flg=0x45000010 (has extras) }, data: package:com.google.android.youtube

[10-27 13:02:46.123 2090:2090 D/Launchy]
packageIntent Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.google.android.youtube cmp=com.google.android.youtube/.app.honeycomb.Shell$HomeActivity }

[10-27 13:02:46.123 2090:2090 I/InstallCatch]
The installed package is: com.google.android.youtube

[10-27 13:02:46.130 1495:1495 D/ImsResolver]
maybeAddedImsService, packageName: com.google.android.youtube

[10-27 13:02:50.920 1495:1495 D/ImsResolver]
maybeAddedImsService, packageName: com.google.android.youtube

[10-27 13:02:50.926 2090:2090 D/Launchy]
intent:Intent { act=android.intent.action.PACKAGE_CHANGED dat=package:com.google.android.youtube flg=0x45000010 (has extras) }, data: package:com.google.android.youtube

[10-27 13:02:50.930 2090:2090 D/Launchy]
packageIntent Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.google.android.youtube cmp=com.google.android.youtube/.app.honeycomb.Shell$HomeActivity }

[10-27 13:02:50.931 2090:2090 I/InstallCatch]
The installed package is: com.google.android.youtube

[10-27 13:03:04.482 2090:2090 D/Launchy]
intent:Intent { act=android.intent.action.PACKAGE_CHANGED dat=package:com.google.android.youtube flg=0x45000010 (has extras) }, data: package:com.google.android.youtube

[10-27 13:03:04.483 2090:2090 D/Launchy]
packageIntent Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.google.android.youtube cmp=com.google.android.youtube/.app.honeycomb.Shell$HomeActivity }

[10-27 13:03:04.483 2090:2090 I/InstallCatch]
The installed package is: com.google.android.youtube

[10-27 13:03:04.489 1495:1495 D/ImsResolver]
maybeAddedImsService, packageName: com.google.android.youtube

[10-27 13:03:13.579 2090:2090 D/Launchy]
intent:Intent { act=android.intent.action.PACKAGE_CHANGED dat=package:com.google.android.youtube flg=0x45000010 (has extras) }, data: package:com.google.android.youtube

[10-27 13:03:13.583 2090:2090 D/Launchy]
packageIntent Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.google.android.youtube cmp=com.google.android.youtube/.app.honeycomb.Shell$HomeActivity }

[10-27 13:03:13.583 2090:2090 I/InstallCatch]
The installed package is: com.google.android.youtube

[10-27 13:03:13.586 1495:1495 D/ImsResolver]
maybeAddedImsService, packageName: com.google.android.youtube

[10-27 13:05:26.563 2294:2380 I/Finsky]
[159] com.google.android.finsky.p2p.e.c(46): App file cannot be read com.google.android.youtube

 -----------------------

Had to paste whole thing

**Comment by zanezam** [comment]
...and going on here: do u still have the problem with latest version? did u try to re-install? this seems to me like beeing a messed installation or issues with magisk itself. btw. sometimes re-installing magisk after wiping it via the magisk uninstaller helps to fix strange issues.
